### ISSUE TITLE
Set lang icon size in html

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#102]
To avoid big flag flickering effect

**Comment by clacote** [comment]
If there is flickering, it's also probably because the source image is too big for our need: maybe it can be resized down, that would also save bandwidth.

**Comment by sdeleuze** [comment]
This is a SVG (vector graphics) file so the size of the image won't impact the bandwith. We could edit it to change the default size, but I think that's better to use `em` size on HTML size in any case to stay proportional with other CSS elements.

**Comment by clacote** [comment]
Right, makes sense, didn't have thought it could be SVG.
