### ISSUE TITLE
[minor] From a blog entry, switching to EN from FR add a double `//` to url

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#105]
On https://mixit-2017.cfapps.io/blog/une-nouvelle-identite-pour-mixit, when clicking on the US flag to switch to English: the URL becomes https://mixit-2017.cfapps.io//en/blog/mixit-has-a-new-visual-identity (see `//en`).
The `//` does not goes away when switching back to French.

This is minor: blog responds fine in EN and FR besides this URL typo.

**Comment by sdeleuze** [comment]
Fixed by updated `BASE_URI` env variable from `https://mixit-2017.cfapps.io/` to `https://mixit-2017.cfapps.io`.
