### ISSUE TITLE
Missing Sponsors on homepage (Worldline, Ippon ...)

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#109]
They are on the sponsors page bot not on the hoempage ...

**Comment by sdeleuze** [comment]
Seems to be a CSS issue since the HTML markup is generated correctly.

**Comment by sdeleuze** [comment]
Another feedback from @mpetitdant : we sold big logos for gold sponsors so would be nice to have bigger logo on sponsor page and if possible on homepage (we could maybe treat gold and other sponsors differently in term of style).

**Comment by clacote** [comment]
According to @javamind, this is probably a SVG rendering issue: https://mix-it.slack.com/archives/siteweb/p1487692601003362

**Comment by sdeleuze** [comment]
Based on our discussion, @javamind will have a look if @doublejess prefer to focus on beautifying the talks pages.
