### ISSUE TITLE
Sponsor does not have a "company name" attribute

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#113]
Some templates use `company` attribute: https://github.com/mix-it/mixit/blob/330b3a324bdf2a6c27c623f5a9fed65b241a8551/src/main/resources/templates/home-sponsor.mustache#L4
But it looks like there is no such attribute in JSON data: https://github.com/mix-it/mixit/blob/master/src/main/resources/data/sponsor/sponsor_mixit16.json

In the meantime, @doublejess is using a placeholder `sponsor.login` in templates.

**Comment by clacote** [comment]
Did we miss something @javamind?

**Comment by javamind** [comment]
The JSON data are not complete
We need to change them but I can't regenerate them because of your changes in these files @clacote, no ?

**Comment by javamind** [comment]
The bug is on the actual website http://www.mix-it.fr/api/member/sponsor

**Comment by clacote** [comment]
No so much changes from my side: https://github.com/mix-it/mixit/commits/master/src/main/resources/data/sponsor/sponsor_mixit16.json
Just a renaming to `MiXiT`, that I can redo later.
You added links, though.

**Comment by javamind** [comment]
Ok I will regenerate the files in a PR and I will apply the same changes

**Comment by clacote** [comment]
And our current sponsor data should not be `mixit16`, but `mixit17`. We should have both different files.

**Comment by clacote** [comment]
Ah OK, sorry. So there is no bug, if the `company` attribute that we thought missing in JSON data is in fact correctly populated by programmatic code?

**Comment by javamind** [comment]
Data files are used to populate the database. To create the sponsor of the 2017 edition, we use  `EventRepository`. The new sponsors are created here with a company name. For the older we search in the database
