### ISSUE TITLE
Populate EventSponsoring from the JSON data set

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#20]
I think `EventSponsoring` should not a be a root `Document` but rather just a `List<EventSponsoring> sponsors` property of each event.

Could you take care of that @javamind ?

**Comment by javamind** [comment]
If you don't declare EventSponsoring like @Document you have no persistance
I will check this behavior

**Comment by sdeleuze** [comment]
Ok let me know, I am not a Spring Data Mongo guru ;-)
