### ISSUE TITLE
Polish sponsors data

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#39]

**Comment by sdeleuze** [comment]
Images should be ok, but we need to add links for the various sponsors.

**Comment by sdeleuze** [comment]
@mpetitdant reported we should add the party sponsor.

**Comment by javamind** [comment]
Fixed with 3447d74376716ff6195bed735c4dd500c5cb30fc

**Comment by sdeleuze** [comment]
@javamind After discussing with @doublejess I reopen this issue. She is working on an updated sponsor page that will display directly on the page the `shortDescription`. But currently some sponsors have `shortDescription` defined, and other `longDescription`. Could you please update the data to make all the sponsors `shortDescription` defined correctly?
