### ISSUE TITLE
Sponsor logos should have a consistent size for a given level

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#40]
At the moment, the sponsors logos have not the same size: Zenika is smaller than others of the same level.
Each level should have maximum and minimum size.

**Comment by sdeleuze** [comment]
They have fix height (defined by level) and auto width, what rule do you think we should apply?

**Comment by clacote** [comment]
Fixed width and max-height would probably be more faire (logos are either square or landscape, but not usually portrait).
