### ISSUE TITLE
Menu not collapsed on mobile

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#41]
On mobile (iOS), the menu is visible and not hidden in the hamburger menu:
![fullsizeoutput_f2a](https://cloud.githubusercontent.com/assets/750715/22629509/b1c69a18-ebe7-11e6-9813-befda313d5aa.jpeg)

**Comment by doublejess** [comment]
I can't reproduce the issue, I tested on various iPhone (SE & 7 both on iOS 10.2). Let me know if you see it again

**Comment by clacote** [comment]
It works now \o/

**Comment by clacote** [comment]
Issue is back. And not just on Safari/iOS, but also on @javamind's Android

**Comment by clacote** [comment]
Even reproductible on desktop with Chrome Device toolbar:
![screenshot from 2017-02-15 14-14-27](https://cloud.githubusercontent.com/assets/750715/22975992/258eeaec-f389-11e6-9e22-28c408d5b13a.png)

**Comment by sdeleuze** [comment]
Oh I think I know why, that's likely because I remove Jquery after discussing with @doublejess ... The question is do we have to include such big library just to close the mobile menu ?

**Comment by clacote** [comment]
Here is the doc I could find: http://foundation.zurb.com/sites/docs/responsive-navigation.html#js-module. But this doesn't tell me if jQuery is required or not.
But there http://foundation.zurb.com/sites/docs/javascript.html, they say that jQuery is required for every JS Foundation component.

**Comment by sdeleuze** [comment]
On http://foundation.zurb.com/sites/docs/ we can see which component require jQuery (JS) or not.
