### ISSUE TITLE
Write a blog post about the new identity and website

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#42]
@doublejess Send me the title and content and I will add it to the `article_mixit.json` file.

**Comment by clacote** [comment]
Maybe we should keep this open until the actual article is embedded in the website.
https://paper.dropbox.com/doc/Une-nouvelle-identit-pour-MiXiT-SIo5dZ5p7Gn2ZJRcIhFJD
Assigned to @sdeleuze.

**Comment by clacote** [comment]
Will (try to) do it, if @sdeleuze is not already on it.

**Comment by sdeleuze** [comment]
I am not on it and that would really help, thanks @clacote !
