### ISSUE TITLE
Redirect to english version for non-french browsers

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#45]
Should require storing the local in session.

**Comment by clacote** [comment]
Shouldn't this be in the 1.0 version?
Without this, what's the default behaviour for a non-French user? He'll see the French version?

**Comment by sdeleuze** [comment]
Replace `/en/` path prefix by `Content-Language` detection + optional `lang` query param de request switching the locale, that will fix #29 as well.

**Comment by sdeleuze** [comment]
It seems we follow [Google guideline](https://support.google.com/webmasters/answer/182192?hl=en) with the current behavior so I plan to keep it as it is.
