### ISSUE TITLE
Add a MiXiT staff page

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#52]
Equivalent of http://cesar.cfapps.io/staff
That's important to introduce the new comers.
We can do a pure template page no strong need to be dynamic.

**Comment by cbouttaz** [comment]
WIP https://github.com/mix-it/mixit/pull/57

**Comment by cbouttaz** [comment]
![capture d ecran 2017-02-12 a 13 35 55](https://cloud.githubusercontent.com/assets/2411582/22862097/58cef176-f128-11e6-93b0-b82743b3b180.png)
![capture d ecran 2017-02-12 a 13 36 07](https://cloud.githubusercontent.com/assets/2411582/22862099/5d5f6e5a-f128-11e6-82ac-1035f5919a04.png)
![capture d ecran 2017-02-12 a 13 36 18](https://cloud.githubusercontent.com/assets/2411582/22862102/617e6e32-f128-11e6-83b0-56be69ea1b5e.png)
