### ISSUE TITLE
Only home as MiXiT favicon

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#66]
![favicon](https://cloud.githubusercontent.com/assets/750715/22764136/208fd364-ee69-11e6-986a-95646bb96a70.gif)

**Comment by cbouttaz** [comment]
What tool do you use @clacote for 🎥  the 💻  ?

**Comment by clacote** [comment]
@cbouttaz: http://www.cockos.com/licecap/ (Mac/Windows only)

**Comment by cbouttaz** [comment]
nice thanks !
