### ISSUE TITLE
Add a MixTeen category on the homepage

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#69]

**Comment by doublejess** [comment]
MixTeen should definitely be included somewhere but I'm not sure it should be a category. Will there be a MixTeen talk? Perhaps a dedicated page would make more sense?

**Comment by clacote** [comment]
MixTeen does not have a dedicated talk (in standard format), but they usually have a workshop for kids on a full afternoon, and show their work at the end in front of everyone.
Until now, they have a dedicated website, managed by themselves: https://mixteen.github.io/

**Comment by titimoby** [comment]
The github.io page was the old one we used.
A dedicated page is the way to go.
Let me know what content you need and where to push it.
I'll work on it with the help of the MixTeen team.

**Comment by sdeleuze** [comment]
I thought about a dedicated page, with the link to access it presented
along other categories since MixTeen is a key part of MiXiT, so I thought
it would be useful to put it there to see in a nutshell what is MiXiT.
There is maybe other options but I like this one. MixTeen event have a
dedicated room and slot, so that would make sense even if it has a more
specific page.

On Fri, Feb 10, 2017 at 12:08 PM, Thierry Chantier <notifications@github.com

**Comment by sdeleuze** [comment]
As discussed with @doublejess, for the 1.0.0 I think that's ok to have just the category visible on the homepage. 1.1.0 will contain a real MixTeen page visible when we click on this category, with editorial content to describe it and later when we will have the planning, the rooms when MixTeen is.

From my experience, people really understand what MiXiT is by looking at the categories so that's critical for MixTeen to be visible here.
