### ISSUE TITLE
Improve editorial content

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#74]

**Comment by clacote** [comment]
- "mais pas que" à supprimer.
- "Pour cette 7ème édition, nous avons choisi d’orienter les conférences autours de thèmes généraux qui nous touchent" : creux.
- La section "Esprit MiXiT" mentionne essentiellement que les _perks_ (crêpes, soirée) : il manque peut-être un truc sur les valeurs de diversité, d'ouverture.
- "lunch de qualité" : _lunch_ n'est pas français.
