### ISSUE TITLE
Sponsors collections should be randomized

### ISSUE THREAD

**Issue by clacote** [mix-it/mixit#90]
Unless the sponsors are voluntarily rendered in an order consistent with a registration order, they should be randomized on each request to not favour one.
- in footer.
- in sponsors page.

**Comment by sdeleuze** [comment]
@javamind Are sponsors listed voluntarily in registration order?

**Comment by clacote** [comment]
(I was trying to randomise (that's why I was trying to build on IntelliJ :)) : PR incoming, Inch'Allah.
