### ISSUE TITLE
Add target="_blank" to all external links in "about" pages

### ISSUE THREAD

**Issue by doublejess** [mix-it/mixit#96]

**Comment by clacote** [comment]
I understand the motivation, but developers largely hate this ("don't force a behavior I can have at will with CTRL+click").
We can do it, though: you're the boss.

**Comment by cbouttaz** [comment]
I havent seen you message, feel free to accept or reject it :)

**Comment by clacote** [comment]
If we're going to implement this, the same behaviour should probably also be on the external links of the sponsors details.

**Comment by doublejess** [comment]
up to you guys, we can leave it as it is
